# Generated by Django 6.0.5 on 2026-05-19 10:10

import django.db.models.deletion
from django.db import migrations, models

def migrate_legacy_skills(apps, schema_editor):
    Job = apps.get_model('company_jobs', 'Job')
    JobSkill = apps.get_model('company_jobs', 'JobSkill')
    for job in Job.objects.all():
        skills_list = job.skills_legacy
        if isinstance(skills_list, list):
            for skill_name in skills_list:
                JobSkill.objects.get_or_create(job=job, skill_name=skill_name)

class Migration(migrations.Migration):

    dependencies = [
        ('company_jobs', '0002_jobcategory_job_category_name_alter_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skills',
            new_name='skills_legacy',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='company_jobs.job')),
            ],
        ),
        migrations.RunPython(migrate_legacy_skills, reverse_code=migrations.RunPython.noop),
    ]
