# Generated by Django 6.0.5 on 2026-05-19 02:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_profiles', '0002_rename_skills_candidateprofile_skills_legacy_and_more'),
        ('company_jobs', '0002_jobcategory_job_category_name_alter_job_category'),
        ('company_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('cv_url', models.URLField(blank=True)),
                ('candidate_status', models.CharField(choices=[('applied', 'Applied'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('recruiter_status', models.CharField(choices=[('reviewing', 'Reviewing'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='reviewing', max_length=20)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_type', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('offline', 'Offline')], max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidate_profiles.candidateprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company_profiles.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company_jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
