# Generated by Django 6.0.5 on 2026-05-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cv_url',
            new_name='resume',
        ),
    ]
