# Generated by Django 6.0.5 on 2026-05-14 03:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_profiles', '0001_initial'),
        ('company_jobs', '0001_initial'),
        ('company_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('last_message', models.CharField(blank=True, max_length=500)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_company', models.IntegerField(default=0)),
                ('unread_candidate', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='candidate_profiles.candidateprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='company_profiles.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='company_jobs.job')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
    ]
