# Generated by Django 5.0.4 on 2026-05-16 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='skills',
            new_name='skills_legacy',
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='candidate_profiles.candidateprofile')),
            ],
            options={
                'db_table': 'candidate_skills',
            },
        ),
    ]
