# Generated by Django 6.0.5 on 2026-05-19 10:09

from django.db import migrations, models

def update_expert_to_advanced(apps, schema_editor):
    CandidateSkill = apps.get_model('candidate_profiles', 'CandidateSkill')
    CandidateSkill.objects.filter(experience_level='expert').update(experience_level='advanced')

class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profiles', '0002_rename_skills_candidateprofile_skills_legacy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateexperience',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='candidateexperience',
            old_name='title',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='title',
            new_name='current_role',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='bio',
            new_name='professional_summary',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='avatar_url',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='resume_url',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='candidateskill',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.RenameField(
            model_name='candidateskill',
            old_name='level',
            new_name='experience_level',
        ),
        migrations.RemoveField(
            model_name='candidateexperience',
            name='years',
        ),
        migrations.AddField(
            model_name='candidateexperience',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.RunPython(update_expert_to_advanced, reverse_code=migrations.RunPython.noop),
    ]
